# Generated by Django 5.0.7 on 2024-11-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='source_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
